### ISSUE TITLE
cBLUE | Process whole workflow with one button click

### ISSUE THREAD

**Issue by jkspring** [parrishOSU/cBLUE.github.io#40]
Would be nice in later versions to run the whole cBLUE process with the click of one button.

Currently we process the sbet and after the sbet is processed there is a pause until we push the process tpu button.

If we could run the whole process from start to finish with one click that would save some babysitting time on waiting for the sbet to process especially for projects with a lot of missions.

**Comment by kiefk** [comment]
Processing now done in one click, pull #69
